### ISSUE TITLE
ERROR: command "pkg-config --modversion libgphoto2" failed

### ISSUE THREAD

**Issue by maikovisky** [rafasgj/tether#1]
Hi,

I used in Windows and Ubuntu and I got the same error.

```
$ python -m pip install -U -r requirements.txt
Collecting gphoto2==2.0.0 (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/6a/2e/8d7b712bc3de6552dd599b57ac400d817c64b4e5630de907981efba460bd/gphoto2-2.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    ERROR: command "pkg-config --modversion libgphoto2" failed
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-1y07C9/gphoto2/setup.py", line 38, in <module>
        cmd, stderr=FNULL, universal_newlines=True).split('.')
      File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
        raise CalledProcessError(retcode, cmd, output=output)
    subprocess.CalledProcessError: Command '['pkg-config', '--modversion', 'libgphoto2']' returned non-zero exit status 1
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-1y07C9/gphoto2/

```

**Comment by maikovisky** [comment]
I used this command: 

`$ sudo apt install libgphoto2-dev`

**Comment by rafasgj** [comment]
Your 'python' executable is linked to Python 2. Try with "python3 -m pip install -U -r requirements.txt".
